In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = pd.read_csv('data\Shark Tank India.csv')
display(data.head())
display(data.columns)

,Season Number,Startup Name,Episode Number,Pitch Number,Season Start,Season End,Original Air Date,Episode Title,Anchor,Industry,...,Invested Guest Name,All Guest Names,Namita Present,Vineeta Present,Anupam Present,Aman Present,Peyush Present,Ritesh Present,Amit Present,Guest Present
0,1,BluePineFoods,1,1,20-Dec-21,4-Feb-22,20-Dec-21,Badlegi Business Ki Tasveer,Rannvijay Singh,Food and Beverage,...,Ashneer Grover,Ashneer Grover,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0
1,1,BoozScooters,1,2,20-Dec-21,4-Feb-22,20-Dec-21,Badlegi Business Ki Tasveer,Rannvijay Singh,Vehicles/Electrical Vehicles,...,Ashneer Grover,Ashneer Grover,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0
2,1,HeartUpMySleeves,1,3,20-Dec-21,4-Feb-22,20-Dec-21,Badlegi Business Ki Tasveer,Rannvijay Singh,Beauty/Fashion,...,NaN,Ashneer Grover,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0
3,1,TagzFoods,2,4,20-Dec-21,4-Feb-22,21-Dec-21,"Insaan, Ideas Aur Sapne",Rannvijay Singh,Food and Beverage,...,Ashneer Grover,Ashneer Grover,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0
4,1,HeadAndHeart,2,5,20-Dec-21,4-Feb-22,21-Dec-21,"Insaan, Ideas Aur Sapne",Rannvijay Singh,Children/Education,...,NaN,Ashneer Grover,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0

Index(['Season Number', 'Startup Name', 'Episode Number', 'Pitch Number',
       'Season Start', 'Season End', 'Original Air Date', 'Episode Title',
       'Anchor', 'Industry', 'Business Description', 'Company Website',
       'Started in', 'Number of Presenters', 'Male Presenters',
       'Female Presenters', 'Transgender Presenters', 'Couple Presenters',
       'Pitchers Average Age', 'Pitchers City', 'Pitchers State',
       'Yearly Revenue', 'Monthly Sales', 'Gross Margin', 'Net Margin',
       'EBITDA', 'Cash Burn', 'SKUs', 'Has Patents', 'Bootstrapped',
       'Part of Match off', 'Original Ask Amount', 'Original Offered Equity',
       'Valuation Requested', 'Received Offer', 'Accepted Offer',
       'Total Deal Amount', 'Total Deal Equity', 'Total Deal Debt',
       'Debt Interest', 'Deal Valuation', 'Number of Sharks in Deal',
       'Deal Has Conditions', 'Royalty Percentage', 'Royalty Recouped Amount',
       'Advisory Shares Equity', 'Namita Investment Amount',
       'Namita Investment Equity', 'Namita Debt Amount',
       'Vineeta Investment Amount', 'Vineeta Investment Equity',
       'Vineeta Debt Amount', 'Anupam Investment Amount',
       'Anupam Investment Equity', 'Anupam Debt Amount',
       'Aman Investment Amount', 'Aman Investment Equity', 'Aman Debt Amount',
       'Peyush Investment Amount', 'Peyush Investment Equity',
       'Peyush Debt Amount', 'Ritesh Investment Amount',
       'Ritesh Investment Equity', 'Ritesh Debt Amount',
       'Amit Investment Amount', 'Amit Investment Equity', 'Amit Debt Amount',
       'Guest Investment Amount', 'Guest Investment Equity',
       'Guest Debt Amount', 'Invested Guest Name', 'All Guest Names',
       'Namita Present', 'Vineeta Present', 'Anupam Present', 'Aman Present',
       'Peyush Present', 'Ritesh Present', 'Amit Present', 'Guest Present'],
      dtype='object')

In [3]:
column_to_work_on = [
    # --- Context & Identifiers ---
    "Season Number", "Season Start", "Industry", "Started in", "Pitchers Average Age", 
    
    # --- Financial Features (Inputs) ---
    "Yearly Revenue", "Monthly Sales", "Gross Margin", "Net Margin", "EBITDA", 
    "Has Patents", "Bootstrapped", "SKUs",
    
    # --- Founder Expectations (The Anchor) ---
    "Original Ask Amount", "Original Offered Equity", "Valuation Requested",
    
    # --- Negotiation Results (Avoid using these to PREDICT Valuation) ---
    "Received Offer", "Accepted Offer", "Number of Sharks in Deal", 
    "Total Deal Amount", "Total Deal Equity","Total Deal Debt",
    "Debt Interest", "Deal Valuation"
]
df = data[column_to_work_on]

display(df.head())

,Season Number,Season Start,Industry,Started in,Pitchers Average Age,Yearly Revenue,Monthly Sales,Gross Margin,Net Margin,EBITDA,...,Original Offered Equity,Valuation Requested,Received Offer,Accepted Offer,Number of Sharks in Deal,Total Deal Amount,Total Deal Equity,Total Deal Debt,Debt Interest,Deal Valuation
0,1,20-Dec-21,Food and Beverage,2016.0,Middle,95.0,8.0,NaN,NaN,NaN,...,5.0,1000.0,1,1.0,3.0,75.0,16.00,NaN,NaN,469.0
1,1,20-Dec-21,Vehicles/Electrical Vehicles,2017.0,Young,4.0,0.4,NaN,NaN,NaN,...,15.0,267.0,1,1.0,2.0,40.0,50.00,NaN,NaN,80.0
2,1,20-Dec-21,Beauty/Fashion,2021.0,Young,NaN,2.0,NaN,NaN,NaN,...,10.0,250.0,1,1.0,2.0,25.0,30.00,NaN,NaN,83.0
3,1,20-Dec-21,Food and Beverage,2019.0,Middle,700.0,NaN,48.0,NaN,NaN,...,1.0,7000.0,1,1.0,1.0,70.0,2.75,NaN,NaN,2545.0
4,1,20-Dec-21,Children/Education,2015.0,Middle,30.0,NaN,NaN,NaN,NaN,...,5.0,1000.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
display(df.isnull().sum())
display(df.shape)

Season Number                 0
Season Start                  0
Industry                     41
Started in                  150
Pitchers Average Age         77
Yearly Revenue              427
Monthly Sales               485
Gross Margin                607
Net Margin                  693
EBITDA                      682
Has Patents                 722
Bootstrapped                634
SKUs                        738
Original Ask Amount           0
Original Offered Equity       0
Valuation Requested           0
Received Offer                0
Accepted Offer              289
Number of Sharks in Deal    355
Total Deal Amount           355
Total Deal Equity           355
Total Deal Debt             705
Debt Interest               722
Deal Valuation              356
dtype: int64

(789, 24)

In [5]:
# Convert 'Season Start' to a datetime object so we can extract the year
# we use 'coerce' to handle any invalid date formats gracefully, which will convert them to NaT (Not a Time)
df['Season Start'] = pd.to_datetime(df['Season Start'], errors='coerce')

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\3031868963.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Season Start'] = pd.to_datetime(df['Season Start'], errors='coerce')
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\3031868963.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Season Start'] = pd.to_datetime(df['Season Start'], errors='coerce')

In [6]:
# Clean the Industry column so grouping works perfectly
df['Industry'] = df['Industry'].fillna('Others').str.strip().str.title()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\2156596861.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Industry'] = df['Industry'].fillna('Others').str.strip().str.title()

In [7]:
# Calculate the median starting year for each specific industry
industry_start_medians = df.groupby('Industry')['Started in'].transform('median')

# Fill the missing 'Started in' values with their respective Industry Median
df['Started in'] = np.where(
    df['Started in'].isna(),
    industry_start_medians,
    df['Started in']
)

# Crucial Step: Convert the years from decimals (e.g., 2019.0) to solid integers (2019)
df['Started in'] = df['Started in'].astype(int)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\16976111.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Started in'] = np.where(
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\16976111.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Started in'] = df['Started in'].astype(int)

In [8]:
# 2. Extract Season Year from 'Season Start' for age calculation
df['Season_Year'] = df['Season Start'].dt.year

# 3. Calculate Company Age (Season Year - Started In)
df['Company Age'] = df['Season_Year'] - df['Started in']

# 4. Handle Edge Cases: Ensure age isn't negative due to same-year starts
# If a company started in 2021 and pitched in 2021, Age is 0 (which is correct)
df['Company Age'] = df['Company Age'].apply(lambda x: max(x, 0))

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\861497974.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Season_Year'] = df['Season Start'].dt.year
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\861497974.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company Age'] = df['Season_Year'] - df['Started in']
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\861497974.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company Age'] = df['Company Age'].apply(lambda x: max(x, 0))

In [9]:

# Forward Mapping: Strings to Numbers
age_mapping = {
    'Young': 0,
    'Middle': 1,
    'Old': 2
}
df['Pitchers Average Age'] = df['Pitchers Average Age'].map(age_mapping)

# Impute missing 'Pitchers Average Age' with the mode of the respective Industry
df['Pitchers Average Age'] = df['Pitchers Average Age'].fillna(
    df.groupby('Industry')['Pitchers Average Age'].transform(
            lambda x: x.mode()[0] if not x.mode().empty else np.nan
        ).round()
)

# # Reverse Mapping: Numbers back to Strings
# reverse_age_mapping = {
#     0.0: 'Young', 
#     1.0: 'Middle', 
#     2.0: 'Old'
# }
# df['Pitchers Average Age'] = df['Pitchers Average Age'].map(reverse_age_mapping)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\3617080606.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Pitchers Average Age'] = df['Pitchers Average Age'].map(age_mapping)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\3617080606.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Pitchers Average Age'] = df['Pitchers Average Age'].fillna(

In [10]:

# Calculate the median revenue for each specific industry
industry_medians = df.groupby('Industry')['Yearly Revenue'].transform('median')

# If Revenue is missing AND the company is <= 1 year old -> Fill with 0
# If Revenue is missing AND company is > 1 year old (or age is unknown) -> Fill Industry Median
# If Revenue is NOT missing -> keep the original Revenue


df['Yearly Revenue'] = np.where(  
    df['Yearly Revenue'].isna() & (df["Company Age"] <= 1), 
    0,
    np.where(
        df['Yearly Revenue'].isna(),
        industry_medians, 
        df['Yearly Revenue'] 
    )
)

df['Yearly Revenue'] = df['Yearly Revenue'].fillna(df['Yearly Revenue'].median())

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\1785017177.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Yearly Revenue'] = np.where(
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\1785017177.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Yearly Revenue'] = df['Yearly Revenue'].fillna(df['Yearly Revenue'].median())

In [11]:
# 1. Calculate the median Monthly Sales for each industry as a fallback
industry_monthly_medians = df.groupby('Industry')['Monthly Sales'].transform('median')

# Condition A: If Yearly Revenue is 0, Monthly Sales is 0
# Condition B: If Monthly Sales is missing but Yearly Revenue exists, divide by 12
# Condition C: If it's STILL missing, use the industry median
# Condition D: Keep the original valid Monthly Sales


df['Monthly Sales'] = np.where(

    df['Yearly Revenue'] == 0, 
    0, 
    np.where(  
        df['Monthly Sales'].isna() & (df['Yearly Revenue'] > 0),
        df['Yearly Revenue'] / 12,
        df['Monthly Sales']
    )
)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\3047813755.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Monthly Sales'] = np.where(

In [12]:
# The "Genius" Save: Convert accidental Markups (>100) into actual Gross Margins
df.loc[df['Gross Margin'] > 100, 'Gross Margin'] = (df['Gross Margin'] / (df['Gross Margin'] + 100)) * 100

# Fill missing values using the specific Industry Median
df['Gross Margin'] = df['Gross Margin'].fillna(
    df.groupby('Industry')['Gross Margin'].transform('median')
)

# The Bulletproof Fallback: Fill any completely empty industries with the overall median
df['Gross Margin'] = df['Gross Margin'].fillna(df['Gross Margin'].median())

df["Gross Margin"] = df["Gross Margin"].astype(float).round(1)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\399144847.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gross Margin'] = df['Gross Margin'].fillna(
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\399144847.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gross Margin'] = df['Gross Margin'].fillna(df['Gross Margin'].median())
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\399144847.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gross Margin"] = df["Gross Margin"].astype(float).round(1)

In [13]:
# Delete mathematically impossible margins (Net > Gross)
df.loc[df['Gross Margin'] < df['Net Margin'], 'Net Margin'] = np.nan

# Fill the now-empty bad data with the specific Industry Median
df['Net Margin'] = df['Net Margin'].fillna(
    df.groupby('Industry')['Net Margin'].transform('median')
)

# Fallback for completely empty industries
df['Net Margin'] = df['Net Margin'].fillna(df['Net Margin'].median())

# This compares the newly filled Net Margin with the company's actual Gross Margin.
# If the imputed Net Margin accidentally exceeds the Gross Margin, it forces it down.
df['Net Margin'] = np.minimum(df['Net Margin'], df['Gross Margin'])

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\2167750004.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Net Margin'] = df['Net Margin'].fillna(
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\2167750004.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Net Margin'] = df['Net Margin'].fillna(df['Net Margin'].median())
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\2167750004.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Net Margin'] = np.minimum(df['Net Margin'], df['Gross Margin'])

In [14]:
# Fill the blanks with the normal operating standard for that specific industry
df['EBITDA'] = df['EBITDA'].fillna(
    df.groupby('Industry')['EBITDA'].transform('median')
)

# If a whole industry was completely blank, use the global median
df['EBITDA'] = df['EBITDA'].fillna(df['EBITDA'].median())

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\2755013029.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['EBITDA'] = df['EBITDA'].fillna(
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\2755013029.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['EBITDA'] = df['EBITDA'].fillna(df['EBITDA'].median())

In [15]:
df['Has Patents'] = df['Has Patents'].map({'yes': 1, 'no': 0}).fillna(0).astype(int)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\450830683.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Has Patents'] = df['Has Patents'].map({'yes': 1, 'no': 0}).fillna(0).astype(int)

In [16]:
df['Bootstrapped'] = df['Bootstrapped'].map({'yes': 1, 'funded': 0}).fillna(0).astype(int)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\2053545878.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Bootstrapped'] = df['Bootstrapped'].map({'yes': 1, 'funded': 0}).fillna(0).astype(int)

In [17]:
# Calculate both the Median and the Mean for each industry
industry_median = df.groupby('Industry')['SKUs'].transform('median')
industry_mean = df.groupby('Industry')['SKUs'].transform('mean')

# Compare them row-by-row and keep the smaller number
conservative_imputation = np.minimum(industry_median, industry_mean)

# Fill the missing SKU values with that conservative number
df['SKUs'] = df['SKUs'].fillna(conservative_imputation)

# If an entire industry was blank, use the global median
df['SKUs'] = df['SKUs'].fillna(df['SKUs'].median())

# Round any floating-point medians (like 4.5 -> 5.0) 
df['SKUs'] = df['SKUs'].round().astype(int)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\2841032392.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['SKUs'] = df['SKUs'].fillna(conservative_imputation)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\2841032392.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['SKUs'] = df['SKUs'].fillna(df['SKUs'].median())
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\2841032392.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['SKUs'] = df['SKUs'].round().astype(int)

In [18]:
df["Accepted Offer"].fillna(0, inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\521929036.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Accepted Offer"].fillna(0, inplace=True)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\521929036.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Accepted Offer"].fillna(0, inplace=True)

In [19]:
# No Debt was involved: 
# The deal was pure equity (e.g., 50 Lakhs for 5% equity), so an interest rate doesn't exist. This is the case for 90% of the pitches.

# Interest-Free Debt: 
# Occasionally, Sharks will offer debt at 0% interest to help the founders with working capital without burdening them with interest payments.

df["Number of Sharks in Deal"] = df["Number of Sharks in Deal"].fillna(0).astype(int)

df["Total Deal Amount"] = df["Total Deal Amount"].fillna(0)
df["Total Deal Equity"] = df["Total Deal Equity"].fillna(0)
df["Total Deal Debt"] = df["Total Deal Debt"].fillna(0)
df['Debt Interest'] = df['Debt Interest'].fillna(0)

df["Deal Valuation"] = df["Deal Valuation"].fillna(0)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\1020421593.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Number of Sharks in Deal"] = df["Number of Sharks in Deal"].fillna(0).astype(int)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\1020421593.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Total Deal Amount"] = df["Total Deal Amount"].fillna(0)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\1020421593.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Total Deal Equity"] = df["Total Deal Equity"].fillna(0)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\1020421593.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Total Deal Debt"] = df["Total Deal Debt"].fillna(0)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\1020421593.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Debt Interest'] = df['Debt Interest'].fillna(0)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\1020421593.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Deal Valuation"] = df["Deal Valuation"].fillna(0)

In [20]:
display(df.isnull().sum())
display(df.shape)

Season Number               0
Season Start                0
Industry                    0
Started in                  0
Pitchers Average Age        0
Yearly Revenue              0
Monthly Sales               0
Gross Margin                0
Net Margin                  0
EBITDA                      0
Has Patents                 0
Bootstrapped                0
SKUs                        0
Original Ask Amount         0
Original Offered Equity     0
Valuation Requested         0
Received Offer              0
Accepted Offer              0
Number of Sharks in Deal    0
Total Deal Amount           0
Total Deal Equity           0
Total Deal Debt             0
Debt Interest               0
Deal Valuation              0
Season_Year                 0
Company Age                 0
dtype: int64

(789, 26)

In [21]:
df.drop(['Started in', 'Season Start', 'Season_Year' ,], axis=1, inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_30516\1172812167.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(['Started in', 'Season Start', 'Season_Year' ,], axis=1, inplace=True)

In [22]:
df.to_excel('data/Cleaned_Shark_Tank_India.xlsx', index=False)